# Generated by Django 6.0.2 on 2026-05-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shop Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('application', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_products/')),
                ('spec_speed', models.CharField(blank=True, max_length=100)),
                ('spec_weight', models.CharField(blank=True, max_length=100)),
                ('spec_voltage', models.CharField(blank=True, max_length=100)),
                ('spec_power', models.CharField(blank=True, max_length=100)),
                ('spec_storage', models.CharField(blank=True, max_length=100)),
                ('spec_connectivity', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shopcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
