# Generated by Django 6.0.2 on 2026-05-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown on the shop page', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_hardcoded', models.BooleanField(default=False, help_text='If True, this tab uses hardcoded products (Automation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Tab',
                'verbose_name_plural': 'Shop Tabs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'ordering': ['tab', 'name'], 'verbose_name_plural': 'Shop Categories'},
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.shoptab'),
        ),
    ]
