# Generated by Django 6.0.2 on 2026-05-09 15:23

from django.db import migrations


def create_default_tabs(apps, schema_editor):
    """Create default tabs for Automation and Solar & Inverters"""
    ShopTab = apps.get_model('shop', 'ShopTab')

    # Create Automation tab (hardcoded, system tab)
    ShopTab.objects.get_or_create(
        name='automation',
        defaults={
            'display_name': 'Automation Products',
            'description': 'Gate automation, swing gate operators, and garage door solutions',
            'order': 0,
            'is_active': True,
            'is_hardcoded': True,
        }
    )

    # Create Solar & Inverters tab (editable by admin)
    ShopTab.objects.get_or_create(
        name='solar-inverters',
        defaults={
            'display_name': 'Solar & Inverters',
            'description': 'Solar panels, inverters, and renewable energy solutions',
            'order': 1,
            'is_active': True,
            'is_hardcoded': False,
        }
    )


def reverse_tabs(apps, schema_editor):
    """Delete the default tabs"""
    ShopTab = apps.get_model('shop', 'ShopTab')
    ShopTab.objects.filter(name__in=['automation', 'solar-inverters']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoptab_alter_shopcategory_options_shopcategory_tab'),
    ]

    operations = [
        migrations.RunPython(create_default_tabs, reverse_tabs),
    ]
