# Generated by Django 6.0.2 on 2026-05-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage_productmodel_productmodelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodelimage',
            name='model',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ProductModelImage',
        ),
    ]
